networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - frontend
    networks:
      - dev

  frontend:
    build:
      context: ./client
    networks:
      - dev