export const DEVICE_TYPES = {
        CONDITIONER: {
            name: 'Кондиционеры',
            params: [
                'AirTemperature',
                'SetpointAirTemperature',
                'SupplyAirTemperature',
                'Humidity',
                'SetpointHumidity',
                'Compressor1Status',
                'Compressor2Status',
                'Eev1Superheat',
                'Eev2Superheat',
                'Eev1ValveOpening',
                'Eev2ValveOpening',
                'HumidifierRunning',
                'Fan1Running',
                'Fan1Speed',
                'MaintenanceYear',
                'MaintenanceMonth',
                'MaintenanceDay',
                'OnOff',
            ]
        },
        DGU: {
            name: 'ДГУ',
            params: [
                'genVoltageL1N',
                'genVoltageL2N',
                'genVoltageL3N',
                'genVoltageL1L2',
                'genVoltageL2L3',
                'genVoltageL1L3',
                'genCurrentL1',
                'genCurrentL2',
                'genCurrentL3',
                'activePowerTotal',
                'reactivePowerTotal',
                'PF',
                'activePowerL1',
                'activePowerL2',
                'activePowerL3',
                'reactivePowerL1',
                'reactivePowerL2',
                'reactivePowerL3',
                'PFL1',
                'PFL2',
                'PFL3',
                'engineSpeed',
                'genFrequency',
                'batteryVoltage',
                'oilPressure',
                'coolantTemp',
                'fuelLevel',
                'gensetMode'
            ]
        },
        MIPS: {
            name: 'МИПС',
            params: [
                'VoltageL1',
                'VoltageL2',
                'VoltageL3',
                'CurrentTotal',
                'CurrentL1',
                'CurrentL2',
                'CurrentL3',
                'FullPowerTotal',
                'FullPowerL1',
                'FullPowerL2',
                'FullPowerL3',
                'ActivePowerTotal',
                'ActivePowerL1',
                'ActivePowerL2',
                'ActivePowerL3',
                'ReactivePowerTotal',
                'ReactivePowerL1',
                'ReactivePowerL2',
                'ReactivePowerL3',
            ]
        },
    USDD: {
            name: 'УСДД',
            params: [
                'input1VoltageAvailable',
                'input2VoltageAvailable',
                'dguVoltageAvailable'
            ]
        }
}